### ISSUE TITLE
to fix

### ISSUE THREAD

**Issue by Gabrieldrc** [DiegoSperandioAR/Ejercicios_de_condicionales#1]
Revisa el archivo "tareaIf.py", los ejercicios:
  Primera Parte:
  - ejercicio 3 (2) "Else"
  - ejercicio 4 "numero" no lo usas(?)
  Segunda Parte:
  - ejercicio 3 falta el "Else"
Tercara Parte:
  - ejercicio 2 falta el "Else"

**Comment by DiegoSperandioAR** [comment]
Resuelto

**Comment by Gabrieldrc** [comment]
Bien
